// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnalysis = `-- name: CreateAnalysis :one
INSERT INTO ai_analyses (id, case_id, version, status, model_name, prompt_version)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, case_id, version, status, technical_retry_count, worker_attempt_id,
          worker_started_at, summary, facts, assumptions, unknowns, risk_analysis,
          compliance_analysis, recommendation, alternatives, missing_information,
          policy_status, evidence_quality, uncertainty, verification_status,
          verification_notes, model_name, prompt_version, created_at`

type CreateAnalysisParams struct {
	ID            pgtype.UUID
	CaseID        pgtype.UUID
	Version       int32
	Status        string
	ModelName     string
	PromptVersion string
}

func (q *Queries) CreateAnalysis(ctx context.Context, arg CreateAnalysisParams) (AiAnalysis, error) {
	row := q.dbx.QueryRow(ctx, createAnalysis, arg.ID, arg.CaseID, arg.Version, arg.Status, arg.ModelName, arg.PromptVersion)
	var i AiAnalysis
	err := row.Scan(
		&i.ID, &i.CaseID, &i.Version, &i.Status, &i.TechnicalRetryCount, &i.WorkerAttemptID,
		&i.WorkerStartedAt, &i.Summary, &i.Facts, &i.Assumptions, &i.Unknowns, &i.RiskAnalysis,
		&i.ComplianceAnalysis, &i.Recommendation, &i.Alternatives, &i.MissingInformation,
		&i.PolicyStatus, &i.EvidenceQuality, &i.Uncertainty, &i.VerificationStatus,
		&i.VerificationNotes, &i.ModelName, &i.PromptVersion, &i.CreatedAt,
	)
	return i, err
}

const getAnalysis = `-- name: GetAnalysis :one
SELECT id, case_id, version, status, technical_retry_count, worker_attempt_id,
       worker_started_at, summary, facts, assumptions, unknowns, risk_analysis,
       compliance_analysis, recommendation, alternatives, missing_information,
       policy_status, evidence_quality, uncertainty, verification_status,
       verification_notes, model_name, prompt_version, created_at
FROM ai_analyses
WHERE id = $1`

func (q *Queries) GetAnalysis(ctx context.Context, id pgtype.UUID) (AiAnalysis, error) {
	row := q.dbx.QueryRow(ctx, getAnalysis, id)
	var i AiAnalysis
	err := row.Scan(
		&i.ID, &i.CaseID, &i.Version, &i.Status, &i.TechnicalRetryCount, &i.WorkerAttemptID,
		&i.WorkerStartedAt, &i.Summary, &i.Facts, &i.Assumptions, &i.Unknowns, &i.RiskAnalysis,
		&i.ComplianceAnalysis, &i.Recommendation, &i.Alternatives, &i.MissingInformation,
		&i.PolicyStatus, &i.EvidenceQuality, &i.Uncertainty, &i.VerificationStatus,
		&i.VerificationNotes, &i.ModelName, &i.PromptVersion, &i.CreatedAt,
	)
	return i, err
}

const getAnalysisForUpdate = `-- name: GetAnalysisForUpdate :one
SELECT id, case_id, version, status, technical_retry_count, worker_attempt_id,
       worker_started_at, summary, facts, assumptions, unknowns, risk_analysis,
       compliance_analysis, recommendation, alternatives, missing_information,
       policy_status, evidence_quality, uncertainty, verification_status,
       verification_notes, model_name, prompt_version, created_at
FROM ai_analyses
WHERE id = $1
FOR UPDATE`

func (q *Queries) GetAnalysisForUpdate(ctx context.Context, id pgtype.UUID) (AiAnalysis, error) {
	row := q.dbx.QueryRow(ctx, getAnalysisForUpdate, id)
	var i AiAnalysis
	err := row.Scan(
		&i.ID, &i.CaseID, &i.Version, &i.Status, &i.TechnicalRetryCount, &i.WorkerAttemptID,
		&i.WorkerStartedAt, &i.Summary, &i.Facts, &i.Assumptions, &i.Unknowns, &i.RiskAnalysis,
		&i.ComplianceAnalysis, &i.Recommendation, &i.Alternatives, &i.MissingInformation,
		&i.PolicyStatus, &i.EvidenceQuality, &i.Uncertainty, &i.VerificationStatus,
		&i.VerificationNotes, &i.ModelName, &i.PromptVersion, &i.CreatedAt,
	)
	return i, err
}

const updateAnalysisResult = `-- name: UpdateAnalysisResult :one
UPDATE ai_analyses
SET status = $2, summary = $3, facts = $4, assumptions = $5, unknowns = $6,
    risk_analysis = $7, compliance_analysis = $8, recommendation = $9,
    alternatives = $10, missing_information = $11, policy_status = $12,
    evidence_quality = $13, uncertainty = $14, verification_status = $15,
    verification_notes = $16
WHERE id = $1
RETURNING id, case_id, version, status, technical_retry_count, worker_attempt_id,
          worker_started_at, summary, facts, assumptions, unknowns, risk_analysis,
          compliance_analysis, recommendation, alternatives, missing_information,
          policy_status, evidence_quality, uncertainty, verification_status,
          verification_notes, model_name, prompt_version, created_at`

type UpdateAnalysisResultParams struct {
	ID                 pgtype.UUID
	Status             string
	Summary            pgtype.Text
	Facts              []byte
	Assumptions        []byte
	Unknowns           []byte
	RiskAnalysis       []byte
	ComplianceAnalysis []byte
	Recommendation     []byte
	Alternatives       []byte
	MissingInformation []byte
	PolicyStatus       pgtype.Text
	EvidenceQuality    pgtype.Text
	Uncertainty        pgtype.Text
	VerificationStatus pgtype.Text
	VerificationNotes  []byte
}

func (q *Queries) UpdateAnalysisResult(ctx context.Context, arg UpdateAnalysisResultParams) (AiAnalysis, error) {
	row := q.dbx.QueryRow(ctx, updateAnalysisResult,
		arg.ID,
		arg.Status,
		arg.Summary,
		arg.Facts,
		arg.Assumptions,
		arg.Unknowns,
		arg.RiskAnalysis,
		arg.ComplianceAnalysis,
		arg.Recommendation,
		arg.Alternatives,
		arg.MissingInformation,
		arg.PolicyStatus,
		arg.EvidenceQuality,
		arg.Uncertainty,
		arg.VerificationStatus,
		arg.VerificationNotes,
	)
	var i AiAnalysis
	err := row.Scan(
		&i.ID, &i.CaseID, &i.Version, &i.Status, &i.TechnicalRetryCount, &i.WorkerAttemptID,
		&i.WorkerStartedAt, &i.Summary, &i.Facts, &i.Assumptions, &i.Unknowns, &i.RiskAnalysis,
		&i.ComplianceAnalysis, &i.Recommendation, &i.Alternatives, &i.MissingInformation,
		&i.PolicyStatus, &i.EvidenceQuality, &i.Uncertainty, &i.VerificationStatus,
		&i.VerificationNotes, &i.ModelName, &i.PromptVersion, &i.CreatedAt,
	)
	return i, err
}
