// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

// Hand-written (BE-032): sqlc generation requires network access that is not
// available in the implementation environment. Keep in sync with
// db/queries/analysis.sql until the next successful make sqlc run.

const createAnalysisPolicyRef = `-- name: CreateAnalysisPolicyRef :one
INSERT INTO analysis_policy_refs (id, analysis_id, policy_version_id, section, excerpt, relevance_score)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, analysis_id, policy_version_id, section, excerpt, relevance_score, created_at`

type CreateAnalysisPolicyRefParams struct {
	ID              pgtype.UUID
	AnalysisID      pgtype.UUID
	PolicyVersionID pgtype.UUID
	Section         pgtype.Text
	Excerpt         pgtype.Text
	RelevanceScore  pgtype.Numeric
}

func (q *Queries) CreateAnalysisPolicyRef(ctx context.Context, arg CreateAnalysisPolicyRefParams) (AnalysisPolicyRef, error) {
	row := q.dbx.QueryRow(ctx, createAnalysisPolicyRef,
		arg.ID, arg.AnalysisID, arg.PolicyVersionID, arg.Section, arg.Excerpt, arg.RelevanceScore,
	)
	var i AnalysisPolicyRef
	err := row.Scan(
		&i.ID, &i.AnalysisID, &i.PolicyVersionID, &i.Section, &i.Excerpt, &i.RelevanceScore, &i.CreatedAt,
	)
	return i, err
}

const createAnalysisEvidenceRef = `-- name: CreateAnalysisEvidenceRef :one
INSERT INTO analysis_evidence_refs (id, analysis_id, evidence_id, usage_type)
VALUES ($1, $2, $3, $4)
RETURNING id, analysis_id, evidence_id, usage_type, created_at`

type CreateAnalysisEvidenceRefParams struct {
	ID         pgtype.UUID
	AnalysisID pgtype.UUID
	EvidenceID pgtype.UUID
	UsageType  string
}

func (q *Queries) CreateAnalysisEvidenceRef(ctx context.Context, arg CreateAnalysisEvidenceRefParams) (AnalysisEvidenceRef, error) {
	row := q.dbx.QueryRow(ctx, createAnalysisEvidenceRef,
		arg.ID, arg.AnalysisID, arg.EvidenceID, arg.UsageType,
	)
	var i AnalysisEvidenceRef
	err := row.Scan(&i.ID, &i.AnalysisID, &i.EvidenceID, &i.UsageType, &i.CreatedAt)
	return i, err
}

const listAnalysisPolicyRefs = `-- name: ListAnalysisPolicyRefs :many
SELECT id, analysis_id, policy_version_id, section, excerpt, relevance_score, created_at
FROM analysis_policy_refs
WHERE analysis_id = $1
ORDER BY created_at ASC, id ASC`

func (q *Queries) ListAnalysisPolicyRefs(ctx context.Context, analysisID pgtype.UUID) ([]AnalysisPolicyRef, error) {
	rows, err := q.dbx.Query(ctx, listAnalysisPolicyRefs, analysisID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]AnalysisPolicyRef, 0)
	for rows.Next() {
		var i AnalysisPolicyRef
		if err := rows.Scan(
			&i.ID, &i.AnalysisID, &i.PolicyVersionID, &i.Section, &i.Excerpt, &i.RelevanceScore, &i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalysisEvidenceRefs = `-- name: ListAnalysisEvidenceRefs :many
SELECT id, analysis_id, evidence_id, usage_type, created_at
FROM analysis_evidence_refs
WHERE analysis_id = $1
ORDER BY created_at ASC, id ASC`

func (q *Queries) ListAnalysisEvidenceRefs(ctx context.Context, analysisID pgtype.UUID) ([]AnalysisEvidenceRef, error) {
	rows, err := q.dbx.Query(ctx, listAnalysisEvidenceRefs, analysisID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]AnalysisEvidenceRef, 0)
	for rows.Next() {
		var i AnalysisEvidenceRef
		if err := rows.Scan(&i.ID, &i.AnalysisID, &i.EvidenceID, &i.UsageType, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
