// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendCaseAuditEvent = `-- name: AppendCaseAuditEvent :one
INSERT INTO audit_events
    (id, scope_type, case_id, event_type, actor_id, actor_role, analysis_id, metadata)
VALUES ($1, 'CASE', $2, $3, $4, $5, $6, $7)
RETURNING id, scope_type, case_id, policy_id, policy_version_id, event_type,
          actor_id, actor_role, analysis_id, metadata, created_at`

type AppendCaseAuditEventParams struct {
	ID         pgtype.UUID
	CaseID     pgtype.UUID
	EventType  string
	ActorID    pgtype.UUID
	ActorRole  pgtype.Text
	AnalysisID pgtype.UUID
	Metadata   []byte
}

func (q *Queries) AppendCaseAuditEvent(ctx context.Context, arg AppendCaseAuditEventParams) (AuditEvent, error) {
	row := q.dbx.QueryRow(ctx, appendCaseAuditEvent, arg.ID, arg.CaseID, arg.EventType, arg.ActorID, arg.ActorRole, arg.AnalysisID, arg.Metadata)
	var i AuditEvent
	err := row.Scan(&i.ID, &i.ScopeType, &i.CaseID, &i.PolicyID, &i.PolicyVersionID, &i.EventType, &i.ActorID, &i.ActorRole, &i.AnalysisID, &i.Metadata, &i.CreatedAt)
	return i, err
}

const appendPolicyAuditEvent = `-- name: AppendPolicyAuditEvent :one
INSERT INTO audit_events
    (id, scope_type, policy_id, policy_version_id, event_type, actor_id, metadata)
VALUES ($1, 'POLICY', $2, $3, $4, $5, $6)
RETURNING id, scope_type, case_id, policy_id, policy_version_id, event_type,
          actor_id, actor_role, analysis_id, metadata, created_at`

type AppendPolicyAuditEventParams struct {
	ID              pgtype.UUID
	PolicyID        pgtype.UUID
	PolicyVersionID pgtype.UUID
	EventType       string
	ActorID         pgtype.UUID
	Metadata        []byte
}

func (q *Queries) AppendPolicyAuditEvent(ctx context.Context, arg AppendPolicyAuditEventParams) (AuditEvent, error) {
	row := q.dbx.QueryRow(ctx, appendPolicyAuditEvent, arg.ID, arg.PolicyID, arg.PolicyVersionID, arg.EventType, arg.ActorID, arg.Metadata)
	var i AuditEvent
	err := row.Scan(&i.ID, &i.ScopeType, &i.CaseID, &i.PolicyID, &i.PolicyVersionID, &i.EventType, &i.ActorID, &i.ActorRole, &i.AnalysisID, &i.Metadata, &i.CreatedAt)
	return i, err
}

const listCaseAuditEvents = `-- name: ListCaseAuditEvents :many
SELECT id, scope_type, case_id, policy_id, policy_version_id, event_type,
       actor_id, actor_role, analysis_id, metadata, created_at
FROM audit_events
WHERE case_id = $1
ORDER BY created_at, id`

func (q *Queries) ListCaseAuditEvents(ctx context.Context, caseID pgtype.UUID) ([]AuditEvent, error) {
	rows, err := q.dbx.Query(ctx, listCaseAuditEvents, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]AuditEvent, 0)
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(&i.ID, &i.ScopeType, &i.CaseID, &i.PolicyID, &i.PolicyVersionID, &i.EventType, &i.ActorID, &i.ActorRole, &i.AnalysisID, &i.Metadata, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
