// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeCase = `-- name: CloseCase :one
UPDATE cases
SET status = 'CLOSED', closed_by = $2, close_reason = $3,
    closed_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, case_number, case_type_id, title, description, urgency, status,
          created_by, owner_id, current_analysis_id, closed_by, close_reason,
          closed_at, created_at, updated_at`

type CloseCaseParams struct {
	ID          pgtype.UUID
	ClosedBy    pgtype.UUID
	CloseReason string
}

func (q *Queries) CloseCase(ctx context.Context, arg CloseCaseParams) (Case, error) {
	row := q.dbx.QueryRow(ctx, closeCase, arg.ID, arg.ClosedBy, arg.CloseReason)
	var i Case
	err := row.Scan(&i.ID, &i.CaseNumber, &i.CaseTypeID, &i.Title, &i.Description, &i.Urgency, &i.Status, &i.CreatedBy, &i.OwnerID, &i.CurrentAnalysisID, &i.ClosedBy, &i.CloseReason, &i.ClosedAt, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const createCase = `-- name: CreateCase :one
INSERT INTO cases (id, case_number, case_type_id, title, description, urgency, created_by, owner_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, case_number, case_type_id, title, description, urgency, status,
          created_by, owner_id, current_analysis_id, closed_by, close_reason,
          closed_at, created_at, updated_at`

type CreateCaseParams struct {
	ID          pgtype.UUID
	CaseNumber  string
	CaseTypeID  pgtype.UUID
	Title       string
	Description string
	Urgency     string
	CreatedBy   pgtype.UUID
	OwnerID     pgtype.UUID
}

func (q *Queries) CreateCase(ctx context.Context, arg CreateCaseParams) (Case, error) {
	row := q.dbx.QueryRow(ctx, createCase, arg.ID, arg.CaseNumber, arg.CaseTypeID, arg.Title, arg.Description, arg.Urgency, arg.CreatedBy, arg.OwnerID)
	var i Case
	err := row.Scan(&i.ID, &i.CaseNumber, &i.CaseTypeID, &i.Title, &i.Description, &i.Urgency, &i.Status, &i.CreatedBy, &i.OwnerID, &i.CurrentAnalysisID, &i.ClosedBy, &i.CloseReason, &i.ClosedAt, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getCase = `-- name: GetCase :one
SELECT id, case_number, case_type_id, title, description, urgency, status,
       created_by, owner_id, current_analysis_id, closed_by, close_reason,
       closed_at, created_at, updated_at
FROM cases
WHERE id = $1`

func (q *Queries) GetCase(ctx context.Context, id pgtype.UUID) (Case, error) {
	row := q.dbx.QueryRow(ctx, getCase, id)
	var i Case
	err := row.Scan(&i.ID, &i.CaseNumber, &i.CaseTypeID, &i.Title, &i.Description, &i.Urgency, &i.Status, &i.CreatedBy, &i.OwnerID, &i.CurrentAnalysisID, &i.ClosedBy, &i.CloseReason, &i.ClosedAt, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getCaseForUpdate = `-- name: GetCaseForUpdate :one
SELECT id, case_number, case_type_id, title, description, urgency, status,
       created_by, owner_id, current_analysis_id, closed_by, close_reason,
       closed_at, created_at, updated_at
FROM cases
WHERE id = $1
FOR UPDATE`

func (q *Queries) GetCaseForUpdate(ctx context.Context, id pgtype.UUID) (Case, error) {
	row := q.dbx.QueryRow(ctx, getCaseForUpdate, id)
	var i Case
	err := row.Scan(&i.ID, &i.CaseNumber, &i.CaseTypeID, &i.Title, &i.Description, &i.Urgency, &i.Status, &i.CreatedBy, &i.OwnerID, &i.CurrentAnalysisID, &i.ClosedBy, &i.CloseReason, &i.ClosedAt, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const listCasesByOwner = `-- name: ListCasesByOwner :many
SELECT id, case_number, case_type_id, title, description, urgency, status,
       created_by, owner_id, current_analysis_id, closed_by, close_reason,
       closed_at, created_at, updated_at
FROM cases
WHERE owner_id = $1
ORDER BY created_at DESC, id DESC`

func (q *Queries) ListCasesByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Case, error) {
	rows, err := q.dbx.Query(ctx, listCasesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]Case, 0)
	for rows.Next() {
		var i Case
		if err := rows.Scan(&i.ID, &i.CaseNumber, &i.CaseTypeID, &i.Title, &i.Description, &i.Urgency, &i.Status, &i.CreatedBy, &i.OwnerID, &i.CurrentAnalysisID, &i.ClosedBy, &i.CloseReason, &i.ClosedAt, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const listCasesForUser = `-- name: ListCasesForUser :many
SELECT c.id, c.case_number, c.case_type_id, c.title, c.description, c.urgency, c.status,
       c.created_by, c.owner_id, c.current_analysis_id, c.closed_by, c.close_reason,
       c.closed_at, c.created_at, c.updated_at
FROM cases AS c
WHERE $1::boolean
   OR EXISTS (
       SELECT 1
       FROM case_participants AS cp
       WHERE cp.case_id = c.id
         AND cp.user_id = $2
         AND cp.status = 'ACTIVE'
   )
ORDER BY c.updated_at DESC, c.created_at DESC, c.id DESC`

type ListCasesForUserParams struct {
	IsAdmin bool
	UserID  pgtype.UUID
}

func (q *Queries) ListCasesForUser(ctx context.Context, arg ListCasesForUserParams) ([]Case, error) {
	rows, err := q.dbx.Query(ctx, listCasesForUser, arg.IsAdmin, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]Case, 0)
	for rows.Next() {
		var i Case
		if err := rows.Scan(&i.ID, &i.CaseNumber, &i.CaseTypeID, &i.Title, &i.Description, &i.Urgency, &i.Status, &i.CreatedBy, &i.OwnerID, &i.CurrentAnalysisID, &i.ClosedBy, &i.CloseReason, &i.ClosedAt, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const updateCase = `-- name: UpdateCase :one
UPDATE cases
SET case_type_id = $1,
    title = $2,
    description = $3,
    urgency = $4,
    updated_at = now()
WHERE id = $5
  AND status = 'DRAFT'
RETURNING id, case_number, case_type_id, title, description, urgency, status,
          created_by, owner_id, current_analysis_id, closed_by, close_reason,
          closed_at, created_at, updated_at`

type UpdateCaseParams struct {
	CaseTypeID  pgtype.UUID
	Title       string
	Description string
	Urgency     string
	ID          pgtype.UUID
}

func (q *Queries) UpdateCase(ctx context.Context, arg UpdateCaseParams) (Case, error) {
	row := q.dbx.QueryRow(ctx, updateCase, arg.CaseTypeID, arg.Title, arg.Description, arg.Urgency, arg.ID)
	var i Case
	err := row.Scan(&i.ID, &i.CaseNumber, &i.CaseTypeID, &i.Title, &i.Description, &i.Urgency, &i.Status, &i.CreatedBy, &i.OwnerID, &i.CurrentAnalysisID, &i.ClosedBy, &i.CloseReason, &i.ClosedAt, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const updateCaseStatus = `-- name: UpdateCaseStatus :one
UPDATE cases
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, case_number, case_type_id, title, description, urgency, status,
          created_by, owner_id, current_analysis_id, closed_by, close_reason,
          closed_at, created_at, updated_at`

type UpdateCaseStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateCaseStatus(ctx context.Context, arg UpdateCaseStatusParams) (Case, error) {
	row := q.dbx.QueryRow(ctx, updateCaseStatus, arg.ID, arg.Status)
	var i Case
	err := row.Scan(&i.ID, &i.CaseNumber, &i.CaseTypeID, &i.Title, &i.Description, &i.Urgency, &i.Status, &i.CreatedBy, &i.OwnerID, &i.CurrentAnalysisID, &i.ClosedBy, &i.CloseReason, &i.ClosedAt, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}
