// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCaseType = `-- name: CreateCaseType :one
INSERT INTO case_types (id, code, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, code, name, description, created_at, updated_at`

type CreateCaseTypeParams struct {
	ID          pgtype.UUID
	Code        string
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateCaseType(ctx context.Context, arg CreateCaseTypeParams) (CaseType, error) {
	row := q.dbx.QueryRow(ctx, createCaseType, arg.ID, arg.Code, arg.Name, arg.Description)
	var i CaseType
	err := row.Scan(&i.ID, &i.Code, &i.Name, &i.Description, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getCaseType = `-- name: GetCaseType :one
SELECT id, code, name, description, created_at, updated_at
FROM case_types
WHERE id = $1`

func (q *Queries) GetCaseType(ctx context.Context, id pgtype.UUID) (CaseType, error) {
	row := q.dbx.QueryRow(ctx, getCaseType, id)
	var i CaseType
	err := row.Scan(&i.ID, &i.Code, &i.Name, &i.Description, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const listCaseTypes = `-- name: ListCaseTypes :many
SELECT id, code, name, description, created_at, updated_at
FROM case_types
ORDER BY name, id`

func (q *Queries) ListCaseTypes(ctx context.Context) ([]CaseType, error) {
	rows, err := q.dbx.Query(ctx, listCaseTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]CaseType, 0)
	for rows.Next() {
		var i CaseType
		if err := rows.Scan(&i.ID, &i.Code, &i.Name, &i.Description, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
