// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDecision = `-- name: CreateDecision :one
INSERT INTO decisions (id, case_id, analysis_id, actor_id, actor_role, decision, reason, comment)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, case_id, analysis_id, actor_id, actor_role, decision, reason, comment, created_at`

type CreateDecisionParams struct {
	ID         pgtype.UUID
	CaseID     pgtype.UUID
	AnalysisID pgtype.UUID
	ActorID    pgtype.UUID
	ActorRole  string
	Decision   string
	Reason     pgtype.Text
	Comment    pgtype.Text
}

func (q *Queries) CreateDecision(ctx context.Context, arg CreateDecisionParams) (Decision, error) {
	row := q.dbx.QueryRow(ctx, createDecision, arg.ID, arg.CaseID, arg.AnalysisID, arg.ActorID, arg.ActorRole, arg.Decision, arg.Reason, arg.Comment)
	var i Decision
	err := row.Scan(&i.ID, &i.CaseID, &i.AnalysisID, &i.ActorID, &i.ActorRole, &i.Decision, &i.Reason, &i.Comment, &i.CreatedAt)
	return i, err
}

const listDecisionsByAnalysis = `-- name: ListDecisionsByAnalysis :many
SELECT id, case_id, analysis_id, actor_id, actor_role, decision, reason, comment, created_at
FROM decisions
WHERE analysis_id = $1
ORDER BY created_at, id`

func (q *Queries) ListDecisionsByAnalysis(ctx context.Context, analysisID pgtype.UUID) ([]Decision, error) {
	rows, err := q.dbx.Query(ctx, listDecisionsByAnalysis, analysisID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]Decision, 0)
	for rows.Next() {
		var i Decision
		if err := rows.Scan(&i.ID, &i.CaseID, &i.AnalysisID, &i.ActorID, &i.ActorRole, &i.Decision, &i.Reason, &i.Comment, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
