// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvidence = `-- name: CreateEvidence :one
INSERT INTO case_evidences
    (id, case_id, source_type, source_user_id, evidence_type, title, content, file_path, mime_type)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, case_id, source_type, source_user_id, evidence_type, title,
          content, file_path, mime_type, created_at`

type CreateEvidenceParams struct {
	ID           pgtype.UUID
	CaseID       pgtype.UUID
	SourceType   string
	SourceUserID pgtype.UUID
	EvidenceType string
	Title        pgtype.Text
	Content      pgtype.Text
	FilePath     pgtype.Text
	MimeType     pgtype.Text
}

func (q *Queries) CreateEvidence(ctx context.Context, arg CreateEvidenceParams) (CaseEvidence, error) {
	row := q.dbx.QueryRow(ctx, createEvidence,
		arg.ID,
		arg.CaseID,
		arg.SourceType,
		arg.SourceUserID,
		arg.EvidenceType,
		arg.Title,
		arg.Content,
		arg.FilePath,
		arg.MimeType,
	)
	var i CaseEvidence
	err := row.Scan(&i.ID, &i.CaseID, &i.SourceType, &i.SourceUserID, &i.EvidenceType, &i.Title, &i.Content, &i.FilePath, &i.MimeType, &i.CreatedAt)
	return i, err
}

const listCaseEvidences = `-- name: ListCaseEvidences :many
SELECT id, case_id, source_type, source_user_id, evidence_type, title,
       content, file_path, mime_type, created_at
FROM case_evidences
WHERE case_id = $1
ORDER BY created_at ASC, id ASC`

func (q *Queries) ListCaseEvidences(ctx context.Context, caseID pgtype.UUID) ([]CaseEvidence, error) {
	rows, err := q.dbx.Query(ctx, listCaseEvidences, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]CaseEvidence, 0)
	for rows.Next() {
		var i CaseEvidence
		if err := rows.Scan(&i.ID, &i.CaseID, &i.SourceType, &i.SourceUserID, &i.EvidenceType, &i.Title, &i.Content, &i.FilePath, &i.MimeType, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
