// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExecution = `-- name: CreateExecution :one
INSERT INTO executions (id, case_id, analysis_id, executer_id, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, case_id, analysis_id, executer_id, status, action_taken, result,
          blocker, started_at, completed_at, created_at`

type CreateExecutionParams struct {
	ID         pgtype.UUID
	CaseID     pgtype.UUID
	AnalysisID pgtype.UUID
	ExecuterID pgtype.UUID
	Status     string
}

func (q *Queries) CreateExecution(ctx context.Context, arg CreateExecutionParams) (Execution, error) {
	row := q.dbx.QueryRow(ctx, createExecution, arg.ID, arg.CaseID, arg.AnalysisID, arg.ExecuterID, arg.Status)
	var i Execution
	err := row.Scan(&i.ID, &i.CaseID, &i.AnalysisID, &i.ExecuterID, &i.Status, &i.ActionTaken, &i.Result, &i.Blocker, &i.StartedAt, &i.CompletedAt, &i.CreatedAt)
	return i, err
}

const existsRunningExecution = `-- name: ExistsRunningExecution :one
SELECT EXISTS(SELECT 1 FROM executions WHERE case_id = $1 AND status = 'IN_PROGRESS')`

func (q *Queries) ExistsRunningExecution(ctx context.Context, caseID pgtype.UUID) (bool, error) {
	row := q.dbx.QueryRow(ctx, existsRunningExecution, caseID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getExecutionForUpdate = `-- name: GetExecutionForUpdate :one
SELECT id, case_id, analysis_id, executer_id, status, action_taken, result,
       blocker, started_at, completed_at, created_at
FROM executions
WHERE id = $1
FOR UPDATE`

func (q *Queries) GetExecutionForUpdate(ctx context.Context, id pgtype.UUID) (Execution, error) {
	row := q.dbx.QueryRow(ctx, getExecutionForUpdate, id)
	var i Execution
	err := row.Scan(&i.ID, &i.CaseID, &i.AnalysisID, &i.ExecuterID, &i.Status, &i.ActionTaken, &i.Result, &i.Blocker, &i.StartedAt, &i.CompletedAt, &i.CreatedAt)
	return i, err
}

const listExecutionsForCase = `-- name: ListExecutionsForCase :many
SELECT id, case_id, analysis_id, executer_id, status, action_taken, result,
       blocker, started_at, completed_at, created_at
FROM executions
WHERE case_id = $1
ORDER BY created_at DESC, id DESC`

func (q *Queries) ListExecutionsForCase(ctx context.Context, caseID pgtype.UUID) ([]Execution, error) {
	rows, err := q.dbx.Query(ctx, listExecutionsForCase, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]Execution, 0)
	for rows.Next() {
		var i Execution
		if err := rows.Scan(&i.ID, &i.CaseID, &i.AnalysisID, &i.ExecuterID, &i.Status, &i.ActionTaken, &i.Result, &i.Blocker, &i.StartedAt, &i.CompletedAt, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const updateExecution = `-- name: UpdateExecution :one
UPDATE executions
SET status = $2, action_taken = $3, result = $4, blocker = $5, completed_at = $6
WHERE id = $1
RETURNING id, case_id, analysis_id, executer_id, status, action_taken, result,
          blocker, started_at, completed_at, created_at`

type UpdateExecutionParams struct {
	ID          pgtype.UUID
	Status      string
	ActionTaken pgtype.Text
	Result      pgtype.Text
	Blocker     pgtype.Text
	CompletedAt pgtype.Timestamptz
}

func (q *Queries) UpdateExecution(ctx context.Context, arg UpdateExecutionParams) (Execution, error) {
	row := q.dbx.QueryRow(ctx, updateExecution, arg.ID, arg.Status, arg.ActionTaken, arg.Result, arg.Blocker, arg.CompletedAt)
	var i Execution
	err := row.Scan(&i.ID, &i.CaseID, &i.AnalysisID, &i.ExecuterID, &i.Status, &i.ActionTaken, &i.Result, &i.Blocker, &i.StartedAt, &i.CompletedAt, &i.CreatedAt)
	return i, err
}
