// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Unit struct {
	ID          pgtype.UUID `json:"id"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type User struct {
	ID          pgtype.UUID `json:"id"`
	UnitID      pgtype.UUID `json:"unit_id"`
	FirebaseUID string      `json:"firebase_uid"`
	Name        string      `json:"name"`
	Email       string      `json:"email"`
	Status      string      `json:"status"`
	SystemRole  string      `json:"system_role"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type CaseType struct {
	ID          pgtype.UUID `json:"id"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type Policy struct {
	ID          pgtype.UUID `json:"id"`
	Code        string      `json:"code"`
	Title       string      `json:"title"`
	Domain      string      `json:"domain"`
	CaseTypeID  pgtype.UUID `json:"case_type_id"`
	Description pgtype.Text `json:"description"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type PolicyVersion struct {
	ID             pgtype.UUID        `json:"id"`
	PolicyID       pgtype.UUID        `json:"policy_id"`
	Version        string             `json:"version"`
	Status         string             `json:"status"`
	IndexStatus    string             `json:"index_status"`
	IndexError     pgtype.Text        `json:"index_error"`
	IndexAttemptID pgtype.UUID        `json:"index_attempt_id"`
	IndexStartedAt pgtype.Timestamptz `json:"index_started_at"`
	IndexedAt      pgtype.Timestamptz `json:"indexed_at"`
	Content        string             `json:"content"`
	FilePath       pgtype.Text        `json:"file_path"`
	EffectiveFrom  pgtype.Timestamptz `json:"effective_from"`
	EffectiveUntil pgtype.Timestamptz `json:"effective_until"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	ApprovedBy     pgtype.UUID        `json:"approved_by"`
	CreatedAt      time.Time          `json:"created_at"`
	ApprovedAt     pgtype.Timestamptz `json:"approved_at"`
}

type Case struct {
	ID                pgtype.UUID        `json:"id"`
	CaseNumber        string             `json:"case_number"`
	CaseTypeID        pgtype.UUID        `json:"case_type_id"`
	Title             string             `json:"title"`
	Description       string             `json:"description"`
	Urgency           string             `json:"urgency"`
	Status            string             `json:"status"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	OwnerID           pgtype.UUID        `json:"owner_id"`
	CurrentAnalysisID pgtype.UUID        `json:"current_analysis_id"`
	ClosedBy          pgtype.UUID        `json:"closed_by"`
	CloseReason       pgtype.Text        `json:"close_reason"`
	ClosedAt          pgtype.Timestamptz `json:"closed_at"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

type CaseParticipant struct {
	ID           pgtype.UUID        `json:"id"`
	CaseID       pgtype.UUID        `json:"case_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Role         string             `json:"role"`
	Required     bool               `json:"required"`
	Status       string             `json:"status"`
	AssignedBy   pgtype.UUID        `json:"assigned_by"`
	AssignedAt   time.Time          `json:"assigned_at"`
	UnassignedAt pgtype.Timestamptz `json:"unassigned_at"`
}

type PolicyChunk struct {
	ID              pgtype.UUID `json:"id"`
	PolicyVersionID pgtype.UUID `json:"policy_version_id"`
	Section         pgtype.Text `json:"section"`
	ChunkIndex      int32       `json:"chunk_index"`
	Content         string      `json:"content"`
	Embedding       pgtype.Text `json:"embedding"`
	CreatedAt       time.Time   `json:"created_at"`
}

type CaseEvidence struct {
	ID           pgtype.UUID `json:"id"`
	CaseID       pgtype.UUID `json:"case_id"`
	SourceType   string      `json:"source_type"`
	SourceUserID pgtype.UUID `json:"source_user_id"`
	EvidenceType string      `json:"evidence_type"`
	Title        pgtype.Text `json:"title"`
	Content      pgtype.Text `json:"content"`
	FilePath     pgtype.Text `json:"file_path"`
	MimeType     pgtype.Text `json:"mime_type"`
	CreatedAt    time.Time   `json:"created_at"`
}

type AiAnalysis struct {
	ID                  pgtype.UUID        `json:"id"`
	CaseID              pgtype.UUID        `json:"case_id"`
	Version             int32              `json:"version"`
	Status              string             `json:"status"`
	TechnicalRetryCount int32              `json:"technical_retry_count"`
	WorkerAttemptID     pgtype.UUID        `json:"worker_attempt_id"`
	WorkerStartedAt     pgtype.Timestamptz `json:"worker_started_at"`
	Summary             pgtype.Text        `json:"summary"`
	Facts               []byte             `json:"facts"`
	Assumptions         []byte             `json:"assumptions"`
	Unknowns            []byte             `json:"unknowns"`
	RiskAnalysis        []byte             `json:"risk_analysis"`
	ComplianceAnalysis  []byte             `json:"compliance_analysis"`
	Recommendation      []byte             `json:"recommendation"`
	Alternatives        []byte             `json:"alternatives"`
	MissingInformation  []byte             `json:"missing_information"`
	PolicyStatus        pgtype.Text        `json:"policy_status"`
	EvidenceQuality     pgtype.Text        `json:"evidence_quality"`
	Uncertainty         pgtype.Text        `json:"uncertainty"`
	VerificationStatus  pgtype.Text        `json:"verification_status"`
	VerificationNotes   []byte             `json:"verification_notes"`
	ModelName           string             `json:"model_name"`
	PromptVersion       string             `json:"prompt_version"`
	CreatedAt           time.Time          `json:"created_at"`
}

type Decision struct {
	ID         pgtype.UUID `json:"id"`
	CaseID     pgtype.UUID `json:"case_id"`
	AnalysisID pgtype.UUID `json:"analysis_id"`
	ActorID    pgtype.UUID `json:"actor_id"`
	ActorRole  string      `json:"actor_role"`
	Decision   string      `json:"decision"`
	Reason     pgtype.Text `json:"reason"`
	Comment    pgtype.Text `json:"comment"`
	CreatedAt  time.Time   `json:"created_at"`
}

type Execution struct {
	ID          pgtype.UUID        `json:"id"`
	CaseID      pgtype.UUID        `json:"case_id"`
	AnalysisID  pgtype.UUID        `json:"analysis_id"`
	ExecuterID  pgtype.UUID        `json:"executer_id"`
	Status      string             `json:"status"`
	ActionTaken pgtype.Text        `json:"action_taken"`
	Result      pgtype.Text        `json:"result"`
	Blocker     pgtype.Text        `json:"blocker"`
	StartedAt   time.Time          `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CreatedAt   time.Time          `json:"created_at"`
}

type OutboxEvent struct {
	ID           pgtype.UUID        `json:"id"`
	CaseID       pgtype.UUID        `json:"case_id"`
	AnalysisID   pgtype.UUID        `json:"analysis_id"`
	EventType    string             `json:"event_type"`
	Payload      []byte             `json:"payload"`
	Status       string             `json:"status"`
	AttemptCount int32              `json:"attempt_count"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
	LastError    pgtype.Text        `json:"last_error"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type AuditEvent struct {
	ID              pgtype.UUID `json:"id"`
	ScopeType       string      `json:"scope_type"`
	CaseID          pgtype.UUID `json:"case_id"`
	PolicyID        pgtype.UUID `json:"policy_id"`
	PolicyVersionID pgtype.UUID `json:"policy_version_id"`
	EventType       string      `json:"event_type"`
	ActorID         pgtype.UUID `json:"actor_id"`
	ActorRole       pgtype.Text `json:"actor_role"`
	AnalysisID      pgtype.UUID `json:"analysis_id"`
	Metadata        []byte      `json:"metadata"`
	CreatedAt       time.Time   `json:"created_at"`
}
