// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (id, case_id, analysis_id, event_type, payload)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, case_id, analysis_id, event_type, payload, status, attempt_count,
          published_at, last_error, created_at, updated_at`

type CreateOutboxEventParams struct {
	ID         pgtype.UUID
	CaseID     pgtype.UUID
	AnalysisID pgtype.UUID
	EventType  string
	Payload    []byte
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.dbx.QueryRow(ctx, createOutboxEvent, arg.ID, arg.CaseID, arg.AnalysisID, arg.EventType, arg.Payload)
	var i OutboxEvent
	err := row.Scan(
		&i.ID, &i.CaseID, &i.AnalysisID, &i.EventType, &i.Payload, &i.Status, &i.AttemptCount,
		&i.PublishedAt, &i.LastError, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const getOutboxEvent = `-- name: GetOutboxEvent :one
SELECT id, case_id, analysis_id, event_type, payload, status, attempt_count,
       published_at, last_error, created_at, updated_at
FROM outbox_events
WHERE id = $1`

func (q *Queries) GetOutboxEvent(ctx context.Context, id pgtype.UUID) (OutboxEvent, error) {
	row := q.dbx.QueryRow(ctx, getOutboxEvent, id)
	var i OutboxEvent
	err := row.Scan(
		&i.ID, &i.CaseID, &i.AnalysisID, &i.EventType, &i.Payload, &i.Status, &i.AttemptCount,
		&i.PublishedAt, &i.LastError, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const listPendingOutboxEventsForUpdate = `-- name: ListPendingOutboxEventsForUpdate :many
SELECT id, case_id, analysis_id, event_type, payload, status, attempt_count,
       published_at, last_error, created_at, updated_at
FROM outbox_events
WHERE status = 'PENDING'
ORDER BY created_at, id
LIMIT $1
FOR UPDATE SKIP LOCKED`

func (q *Queries) ListPendingOutboxEventsForUpdate(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.dbx.Query(ctx, listPendingOutboxEventsForUpdate, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]OutboxEvent, 0)
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID, &i.CaseID, &i.AnalysisID, &i.EventType, &i.Payload, &i.Status, &i.AttemptCount,
			&i.PublishedAt, &i.LastError, &i.CreatedAt, &i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :one
UPDATE outbox_events
SET status = 'PUBLISHED', published_at = $2, updated_at = now(), last_error = NULL
WHERE id = $1
RETURNING id, case_id, analysis_id, event_type, payload, status, attempt_count,
          published_at, last_error, created_at, updated_at`

type MarkOutboxEventPublishedParams struct {
	ID          pgtype.UUID
	PublishedAt pgtype.Timestamptz
}

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, arg MarkOutboxEventPublishedParams) (OutboxEvent, error) {
	row := q.dbx.QueryRow(ctx, markOutboxEventPublished, arg.ID, arg.PublishedAt)
	var i OutboxEvent
	err := row.Scan(
		&i.ID, &i.CaseID, &i.AnalysisID, &i.EventType, &i.Payload, &i.Status, &i.AttemptCount,
		&i.PublishedAt, &i.LastError, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const recordOutboxAttempt = `-- name: RecordOutboxAttempt :one
UPDATE outbox_events
SET attempt_count = attempt_count + 1, last_error = $2, updated_at = now()
WHERE id = $1
RETURNING id, case_id, analysis_id, event_type, payload, status, attempt_count,
          published_at, last_error, created_at, updated_at`

type RecordOutboxAttemptParams struct {
	ID        pgtype.UUID
	LastError pgtype.Text
}

func (q *Queries) RecordOutboxAttempt(ctx context.Context, arg RecordOutboxAttemptParams) (OutboxEvent, error) {
	row := q.dbx.QueryRow(ctx, recordOutboxAttempt, arg.ID, arg.LastError)
	var i OutboxEvent
	err := row.Scan(
		&i.ID, &i.CaseID, &i.AnalysisID, &i.EventType, &i.Payload, &i.Status, &i.AttemptCount,
		&i.PublishedAt, &i.LastError, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}
