// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCaseParticipant = `-- name: CreateCaseParticipant :one
INSERT INTO case_participants (id, case_id, user_id, role, required, assigned_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, case_id, user_id, role, required, status, assigned_by,
          assigned_at, unassigned_at`

type CreateCaseParticipantParams struct {
	ID         pgtype.UUID
	CaseID     pgtype.UUID
	UserID     pgtype.UUID
	Role       string
	Required   bool
	AssignedBy pgtype.UUID
}

func (q *Queries) CreateCaseParticipant(ctx context.Context, arg CreateCaseParticipantParams) (CaseParticipant, error) {
	row := q.dbx.QueryRow(ctx, createCaseParticipant, arg.ID, arg.CaseID, arg.UserID, arg.Role, arg.Required, arg.AssignedBy)
	var i CaseParticipant
	err := row.Scan(&i.ID, &i.CaseID, &i.UserID, &i.Role, &i.Required, &i.Status, &i.AssignedBy, &i.AssignedAt, &i.UnassignedAt)
	return i, err
}

const getActiveParticipantForUpdate = `-- name: GetActiveParticipantForUpdate :one
SELECT id, case_id, user_id, role, required, status, assigned_by,
       assigned_at, unassigned_at
FROM case_participants
WHERE id = $1 AND status = 'ACTIVE'
FOR UPDATE`

func (q *Queries) GetActiveParticipantForUpdate(ctx context.Context, id pgtype.UUID) (CaseParticipant, error) {
	row := q.dbx.QueryRow(ctx, getActiveParticipantForUpdate, id)
	var i CaseParticipant
	err := row.Scan(&i.ID, &i.CaseID, &i.UserID, &i.Role, &i.Required, &i.Status, &i.AssignedBy, &i.AssignedAt, &i.UnassignedAt)
	return i, err
}

const isActiveCaseParticipant = `-- name: IsActiveCaseParticipant :one
SELECT EXISTS (
    SELECT 1
    FROM case_participants
    WHERE case_id = $1
      AND user_id = $2
      AND status = 'ACTIVE'
) AS is_participant`

type IsActiveCaseParticipantParams struct {
	CaseID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) IsActiveCaseParticipant(ctx context.Context, arg IsActiveCaseParticipantParams) (bool, error) {
	row := q.dbx.QueryRow(ctx, isActiveCaseParticipant, arg.CaseID, arg.UserID)
	var is_participant bool
	err := row.Scan(&is_participant)
	return is_participant, err
}

const listCaseParticipants = `-- name: ListCaseParticipants :many
SELECT id, case_id, user_id, role, required, status, assigned_by,
       assigned_at, unassigned_at
FROM case_participants
WHERE case_id = $1
ORDER BY assigned_at, id`

func (q *Queries) ListCaseParticipants(ctx context.Context, caseID pgtype.UUID) ([]CaseParticipant, error) {
	rows, err := q.dbx.Query(ctx, listCaseParticipants, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]CaseParticipant, 0)
	for rows.Next() {
		var i CaseParticipant
		if err := rows.Scan(&i.ID, &i.CaseID, &i.UserID, &i.Role, &i.Required, &i.Status, &i.AssignedBy, &i.AssignedAt, &i.UnassignedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const unassignCaseParticipant = `-- name: UnassignCaseParticipant :one
UPDATE case_participants
SET status = 'INACTIVE', unassigned_at = now()
WHERE id = $1 AND status = 'ACTIVE'
RETURNING id, case_id, user_id, role, required, status, assigned_by,
          assigned_at, unassigned_at`

func (q *Queries) UnassignCaseParticipant(ctx context.Context, id pgtype.UUID) (CaseParticipant, error) {
	row := q.dbx.QueryRow(ctx, unassignCaseParticipant, id)
	var i CaseParticipant
	err := row.Scan(&i.ID, &i.CaseID, &i.UserID, &i.Role, &i.Required, &i.Status, &i.AssignedBy, &i.AssignedAt, &i.UnassignedAt)
	return i, err
}
