// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPolicyVersionIndex = `-- name: ClaimPolicyVersionIndex :one
UPDATE policy_versions
SET index_status = 'PROCESSING',
    index_attempt_id = $2,
    index_started_at = now(),
    index_error = NULL,
    indexed_at = NULL
WHERE id = $1
RETURNING id, policy_id, version, status, index_status, index_error, index_attempt_id,
          index_started_at, indexed_at, content, file_path, effective_from,
          effective_until, created_by, approved_by, created_at, approved_at`

type ClaimPolicyVersionIndexParams struct {
	ID             pgtype.UUID
	IndexAttemptID pgtype.UUID
}

func (q *Queries) ClaimPolicyVersionIndex(ctx context.Context, arg ClaimPolicyVersionIndexParams) (PolicyVersion, error) {
	row := q.dbx.QueryRow(ctx, claimPolicyVersionIndex, arg.ID, arg.IndexAttemptID)
	var i PolicyVersion
	err := row.Scan(
		&i.ID, &i.PolicyID, &i.Version, &i.Status, &i.IndexStatus, &i.IndexError, &i.IndexAttemptID,
		&i.IndexStartedAt, &i.IndexedAt, &i.Content, &i.FilePath, &i.EffectiveFrom,
		&i.EffectiveUntil, &i.CreatedBy, &i.ApprovedBy, &i.CreatedAt, &i.ApprovedAt,
	)
	return i, err
}

const completePolicyVersionIndex = `-- name: CompletePolicyVersionIndex :one
UPDATE policy_versions
SET index_status = $2,
    index_error = $3,
    indexed_at = CASE WHEN $2 = 'READY' THEN now() ELSE indexed_at END
WHERE id = $1 AND index_attempt_id = $4
RETURNING id, policy_id, version, status, index_status, index_error, index_attempt_id,
          index_started_at, indexed_at, content, file_path, effective_from,
          effective_until, created_by, approved_by, created_at, approved_at`

type CompletePolicyVersionIndexParams struct {
	ID             pgtype.UUID
	IndexStatus    string
	IndexError     pgtype.Text
	IndexAttemptID pgtype.UUID
}

func (q *Queries) CompletePolicyVersionIndex(ctx context.Context, arg CompletePolicyVersionIndexParams) (PolicyVersion, error) {
	row := q.dbx.QueryRow(ctx, completePolicyVersionIndex, arg.ID, arg.IndexStatus, arg.IndexError, arg.IndexAttemptID)
	var i PolicyVersion
	err := row.Scan(
		&i.ID, &i.PolicyID, &i.Version, &i.Status, &i.IndexStatus, &i.IndexError, &i.IndexAttemptID,
		&i.IndexStartedAt, &i.IndexedAt, &i.Content, &i.FilePath, &i.EffectiveFrom,
		&i.EffectiveUntil, &i.CreatedBy, &i.ApprovedBy, &i.CreatedAt, &i.ApprovedAt,
	)
	return i, err
}

const createPolicy = `-- name: CreatePolicy :one
INSERT INTO policies (id, code, title, domain, case_type_id, description)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, code, title, domain, case_type_id, description, created_at, updated_at`

type CreatePolicyParams struct {
	ID          pgtype.UUID
	Code        string
	Title       string
	Domain      string
	CaseTypeID  pgtype.UUID
	Description pgtype.Text
}

func (q *Queries) CreatePolicy(ctx context.Context, arg CreatePolicyParams) (Policy, error) {
	row := q.dbx.QueryRow(ctx, createPolicy, arg.ID, arg.Code, arg.Title, arg.Domain, arg.CaseTypeID, arg.Description)
	var i Policy
	err := row.Scan(&i.ID, &i.Code, &i.Title, &i.Domain, &i.CaseTypeID, &i.Description, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const createPolicyChunk = `-- name: CreatePolicyChunk :one
INSERT INTO policy_chunks (id, policy_version_id, section, chunk_index, content, embedding)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, policy_version_id, section, chunk_index, content, embedding, created_at`

type CreatePolicyChunkParams struct {
	ID              pgtype.UUID
	PolicyVersionID pgtype.UUID
	Section         pgtype.Text
	ChunkIndex      int32
	Content         string
	// Embedding is a pgvector text literal in the form "[v1,v2,...]".
	Embedding string
}

func (q *Queries) CreatePolicyChunk(ctx context.Context, arg CreatePolicyChunkParams) (PolicyChunk, error) {
	row := q.dbx.QueryRow(ctx, createPolicyChunk,
		arg.ID,
		arg.PolicyVersionID,
		arg.Section,
		arg.ChunkIndex,
		arg.Content,
		arg.Embedding,
	)
	var i PolicyChunk
	err := row.Scan(&i.ID, &i.PolicyVersionID, &i.Section, &i.ChunkIndex, &i.Content, &i.Embedding, &i.CreatedAt)
	return i, err
}

const createPolicyVersion = `-- name: CreatePolicyVersion :one
INSERT INTO policy_versions (id, policy_id, version, content, file_path, created_by, effective_from, effective_until)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, policy_id, version, status, index_status, index_error, index_attempt_id,
          index_started_at, indexed_at, content, file_path, effective_from,
          effective_until, created_by, approved_by, created_at, approved_at`

type CreatePolicyVersionParams struct {
	ID             pgtype.UUID
	PolicyID       pgtype.UUID
	Version        string
	Content        string
	FilePath       pgtype.Text
	CreatedBy      pgtype.UUID
	EffectiveFrom  pgtype.Timestamptz
	EffectiveUntil pgtype.Timestamptz
}

func (q *Queries) CreatePolicyVersion(ctx context.Context, arg CreatePolicyVersionParams) (PolicyVersion, error) {
	row := q.dbx.QueryRow(ctx, createPolicyVersion, arg.ID, arg.PolicyID, arg.Version, arg.Content, arg.FilePath, arg.CreatedBy, arg.EffectiveFrom, arg.EffectiveUntil)
	var i PolicyVersion
	err := row.Scan(
		&i.ID, &i.PolicyID, &i.Version, &i.Status, &i.IndexStatus, &i.IndexError, &i.IndexAttemptID,
		&i.IndexStartedAt, &i.IndexedAt, &i.Content, &i.FilePath, &i.EffectiveFrom,
		&i.EffectiveUntil, &i.CreatedBy, &i.ApprovedBy, &i.CreatedAt, &i.ApprovedAt,
	)
	return i, err
}

const deletePolicyChunks = `-- name: DeletePolicyChunks :exec
DELETE FROM policy_chunks WHERE policy_version_id = $1`

func (q *Queries) DeletePolicyChunks(ctx context.Context, policyVersionID pgtype.UUID) error {
	_, err := q.dbx.Exec(ctx, deletePolicyChunks, policyVersionID)
	return err
}

const getActivePolicyVersion = `-- name: GetActivePolicyVersion :one
SELECT id, policy_id, version, status, index_status, index_error, index_attempt_id,
       index_started_at, indexed_at, content, file_path, effective_from,
       effective_until, created_by, approved_by, created_at, approved_at
FROM policy_versions
WHERE policy_id = $1 AND status = 'ACTIVE'`

func (q *Queries) GetActivePolicyVersion(ctx context.Context, policyID pgtype.UUID) (PolicyVersion, error) {
	row := q.dbx.QueryRow(ctx, getActivePolicyVersion, policyID)
	var i PolicyVersion
	err := row.Scan(
		&i.ID, &i.PolicyID, &i.Version, &i.Status, &i.IndexStatus, &i.IndexError, &i.IndexAttemptID,
		&i.IndexStartedAt, &i.IndexedAt, &i.Content, &i.FilePath, &i.EffectiveFrom,
		&i.EffectiveUntil, &i.CreatedBy, &i.ApprovedBy, &i.CreatedAt, &i.ApprovedAt,
	)
	return i, err
}

const getActivePolicyVersionForUpdate = `-- name: GetActivePolicyVersionForUpdate :one
SELECT id, policy_id, version, status, index_status, index_error, index_attempt_id,
       index_started_at, indexed_at, content, file_path, effective_from,
       effective_until, created_by, approved_by, created_at, approved_at
FROM policy_versions
WHERE policy_id = $1 AND status = 'ACTIVE'
FOR UPDATE`

func (q *Queries) GetActivePolicyVersionForUpdate(ctx context.Context, policyID pgtype.UUID) (PolicyVersion, error) {
	row := q.dbx.QueryRow(ctx, getActivePolicyVersionForUpdate, policyID)
	var i PolicyVersion
	err := row.Scan(
		&i.ID, &i.PolicyID, &i.Version, &i.Status, &i.IndexStatus, &i.IndexError, &i.IndexAttemptID,
		&i.IndexStartedAt, &i.IndexedAt, &i.Content, &i.FilePath, &i.EffectiveFrom,
		&i.EffectiveUntil, &i.CreatedBy, &i.ApprovedBy, &i.CreatedAt, &i.ApprovedAt,
	)
	return i, err
}

const getPolicy = `-- name: GetPolicy :one
SELECT id, code, title, domain, case_type_id, description, created_at, updated_at
FROM policies
WHERE id = $1`

func (q *Queries) GetPolicy(ctx context.Context, id pgtype.UUID) (Policy, error) {
	row := q.dbx.QueryRow(ctx, getPolicy, id)
	var i Policy
	err := row.Scan(&i.ID, &i.Code, &i.Title, &i.Domain, &i.CaseTypeID, &i.Description, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getPolicyVersion = `-- name: GetPolicyVersion :one
SELECT id, policy_id, version, status, index_status, index_error, index_attempt_id,
       index_started_at, indexed_at, content, file_path, effective_from,
       effective_until, created_by, approved_by, created_at, approved_at
FROM policy_versions
WHERE id = $1`

func (q *Queries) GetPolicyVersion(ctx context.Context, id pgtype.UUID) (PolicyVersion, error) {
	row := q.dbx.QueryRow(ctx, getPolicyVersion, id)
	var i PolicyVersion
	err := row.Scan(
		&i.ID, &i.PolicyID, &i.Version, &i.Status, &i.IndexStatus, &i.IndexError, &i.IndexAttemptID,
		&i.IndexStartedAt, &i.IndexedAt, &i.Content, &i.FilePath, &i.EffectiveFrom,
		&i.EffectiveUntil, &i.CreatedBy, &i.ApprovedBy, &i.CreatedAt, &i.ApprovedAt,
	)
	return i, err
}

const getPolicyVersionForUpdate = `-- name: GetPolicyVersionForUpdate :one
SELECT id, policy_id, version, status, index_status, index_error, index_attempt_id,
       index_started_at, indexed_at, content, file_path, effective_from,
       effective_until, created_by, approved_by, created_at, approved_at
FROM policy_versions
WHERE id = $1
FOR UPDATE`

func (q *Queries) GetPolicyVersionForUpdate(ctx context.Context, id pgtype.UUID) (PolicyVersion, error) {
	row := q.dbx.QueryRow(ctx, getPolicyVersionForUpdate, id)
	var i PolicyVersion
	err := row.Scan(
		&i.ID, &i.PolicyID, &i.Version, &i.Status, &i.IndexStatus, &i.IndexError, &i.IndexAttemptID,
		&i.IndexStartedAt, &i.IndexedAt, &i.Content, &i.FilePath, &i.EffectiveFrom,
		&i.EffectiveUntil, &i.CreatedBy, &i.ApprovedBy, &i.CreatedAt, &i.ApprovedAt,
	)
	return i, err
}

const listPolicies = `-- name: ListPolicies :many
SELECT id, code, title, domain, case_type_id, description, created_at, updated_at
FROM policies
ORDER BY title, id`

func (q *Queries) ListPolicies(ctx context.Context) ([]Policy, error) {
	rows, err := q.dbx.Query(ctx, listPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]Policy, 0)
	for rows.Next() {
		var i Policy
		if err := rows.Scan(&i.ID, &i.Code, &i.Title, &i.Domain, &i.CaseTypeID, &i.Description, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const listPolicyChunks = `-- name: ListPolicyChunks :many
SELECT id, policy_version_id, section, chunk_index, content, embedding, created_at
FROM policy_chunks
WHERE policy_version_id = $1
ORDER BY chunk_index, id`

func (q *Queries) ListPolicyChunks(ctx context.Context, policyVersionID pgtype.UUID) ([]PolicyChunk, error) {
	rows, err := q.dbx.Query(ctx, listPolicyChunks, policyVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]PolicyChunk, 0)
	for rows.Next() {
		var i PolicyChunk
		if err := rows.Scan(&i.ID, &i.PolicyVersionID, &i.Section, &i.ChunkIndex, &i.Content, &i.Embedding, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const listPolicyVersions = `-- name: ListPolicyVersions :many
SELECT id, policy_id, version, status, index_status, index_error, index_attempt_id,
       index_started_at, indexed_at, content, file_path, effective_from,
       effective_until, created_by, approved_by, created_at, approved_at
FROM policy_versions
WHERE policy_id = $1
ORDER BY created_at, id`

func (q *Queries) ListPolicyVersions(ctx context.Context, policyID pgtype.UUID) ([]PolicyVersion, error) {
	rows, err := q.dbx.Query(ctx, listPolicyVersions, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]PolicyVersion, 0)
	for rows.Next() {
		var i PolicyVersion
		if err := rows.Scan(
			&i.ID, &i.PolicyID, &i.Version, &i.Status, &i.IndexStatus, &i.IndexError, &i.IndexAttemptID,
			&i.IndexStartedAt, &i.IndexedAt, &i.Content, &i.FilePath, &i.EffectiveFrom,
			&i.EffectiveUntil, &i.CreatedBy, &i.ApprovedBy, &i.CreatedAt, &i.ApprovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const updatePolicyVersionStatus = `-- name: UpdatePolicyVersionStatus :one
UPDATE policy_versions
SET status = $2
WHERE id = $1
RETURNING id, policy_id, version, status, index_status, index_error, index_attempt_id,
          index_started_at, indexed_at, content, file_path, effective_from,
          effective_until, created_by, approved_by, created_at, approved_at`

type UpdatePolicyVersionStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdatePolicyVersionStatus(ctx context.Context, arg UpdatePolicyVersionStatusParams) (PolicyVersion, error) {
	row := q.dbx.QueryRow(ctx, updatePolicyVersionStatus, arg.ID, arg.Status)
	var i PolicyVersion
	err := row.Scan(
		&i.ID, &i.PolicyID, &i.Version, &i.Status, &i.IndexStatus, &i.IndexError, &i.IndexAttemptID,
		&i.IndexStartedAt, &i.IndexedAt, &i.Content, &i.FilePath, &i.EffectiveFrom,
		&i.EffectiveUntil, &i.CreatedBy, &i.ApprovedBy, &i.CreatedAt, &i.ApprovedAt,
	)
	return i, err
}
