// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPolicy = `-- name: CreatePolicy :one
INSERT INTO policies (id, code, title, domain, case_type_id, description)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, code, title, domain, case_type_id, description, created_at, updated_at`

type CreatePolicyParams struct {
	ID          pgtype.UUID
	Code        string
	Title       string
	Domain      string
	CaseTypeID  pgtype.UUID
	Description pgtype.Text
}

func (q *Queries) CreatePolicy(ctx context.Context, arg CreatePolicyParams) (Policy, error) {
	row := q.dbx.QueryRow(ctx, createPolicy, arg.ID, arg.Code, arg.Title, arg.Domain, arg.CaseTypeID, arg.Description)
	var i Policy
	err := row.Scan(&i.ID, &i.Code, &i.Title, &i.Domain, &i.CaseTypeID, &i.Description, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const createPolicyVersion = `-- name: CreatePolicyVersion :one
INSERT INTO policy_versions (id, policy_id, version, content, file_path, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, policy_id, version, status, index_status, index_error, index_attempt_id,
          index_started_at, indexed_at, content, file_path, effective_from,
          effective_until, created_by, approved_by, created_at, approved_at`

type CreatePolicyVersionParams struct {
	ID        pgtype.UUID
	PolicyID  pgtype.UUID
	Version   string
	Content   string
	FilePath  pgtype.Text
	CreatedBy pgtype.UUID
}

func (q *Queries) CreatePolicyVersion(ctx context.Context, arg CreatePolicyVersionParams) (PolicyVersion, error) {
	row := q.dbx.QueryRow(ctx, createPolicyVersion, arg.ID, arg.PolicyID, arg.Version, arg.Content, arg.FilePath, arg.CreatedBy)
	var i PolicyVersion
	err := row.Scan(
		&i.ID, &i.PolicyID, &i.Version, &i.Status, &i.IndexStatus, &i.IndexError, &i.IndexAttemptID,
		&i.IndexStartedAt, &i.IndexedAt, &i.Content, &i.FilePath, &i.EffectiveFrom,
		&i.EffectiveUntil, &i.CreatedBy, &i.ApprovedBy, &i.CreatedAt, &i.ApprovedAt,
	)
	return i, err
}

const getPolicy = `-- name: GetPolicy :one
SELECT id, code, title, domain, case_type_id, description, created_at, updated_at
FROM policies
WHERE id = $1`

func (q *Queries) GetPolicy(ctx context.Context, id pgtype.UUID) (Policy, error) {
	row := q.dbx.QueryRow(ctx, getPolicy, id)
	var i Policy
	err := row.Scan(&i.ID, &i.Code, &i.Title, &i.Domain, &i.CaseTypeID, &i.Description, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getPolicyVersionForUpdate = `-- name: GetPolicyVersionForUpdate :one
SELECT id, policy_id, version, status, index_status, index_error, index_attempt_id,
       index_started_at, indexed_at, content, file_path, effective_from,
       effective_until, created_by, approved_by, created_at, approved_at
FROM policy_versions
WHERE id = $1
FOR UPDATE`

func (q *Queries) GetPolicyVersionForUpdate(ctx context.Context, id pgtype.UUID) (PolicyVersion, error) {
	row := q.dbx.QueryRow(ctx, getPolicyVersionForUpdate, id)
	var i PolicyVersion
	err := row.Scan(
		&i.ID, &i.PolicyID, &i.Version, &i.Status, &i.IndexStatus, &i.IndexError, &i.IndexAttemptID,
		&i.IndexStartedAt, &i.IndexedAt, &i.Content, &i.FilePath, &i.EffectiveFrom,
		&i.EffectiveUntil, &i.CreatedBy, &i.ApprovedBy, &i.CreatedAt, &i.ApprovedAt,
	)
	return i, err
}

const listPolicies = `-- name: ListPolicies :many
SELECT id, code, title, domain, case_type_id, description, created_at, updated_at
FROM policies
ORDER BY title, id`

func (q *Queries) ListPolicies(ctx context.Context) ([]Policy, error) {
	rows, err := q.dbx.Query(ctx, listPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]Policy, 0)
	for rows.Next() {
		var i Policy
		if err := rows.Scan(&i.ID, &i.Code, &i.Title, &i.Domain, &i.CaseTypeID, &i.Description, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const listPolicyChunks = `-- name: ListPolicyChunks :many
SELECT id, policy_version_id, section, chunk_index, content, embedding, created_at
FROM policy_chunks
WHERE policy_version_id = $1
ORDER BY chunk_index, id`

func (q *Queries) ListPolicyChunks(ctx context.Context, policyVersionID pgtype.UUID) ([]PolicyChunk, error) {
	rows, err := q.dbx.Query(ctx, listPolicyChunks, policyVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]PolicyChunk, 0)
	for rows.Next() {
		var i PolicyChunk
		if err := rows.Scan(&i.ID, &i.PolicyVersionID, &i.Section, &i.ChunkIndex, &i.Content, &i.Embedding, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
