// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateUnit(context.Context, CreateUnitParams) (Unit, error)
	CreateUser(context.Context, CreateUserParams) (User, error)
	GetUnit(context.Context, pgtype.UUID) (Unit, error)
	GetUser(context.Context, pgtype.UUID) (User, error)
	GetUserByFirebaseUID(context.Context, string) (User, error)
	ListUnits(context.Context) ([]Unit, error)
	ListUsersByUnit(context.Context, pgtype.UUID) ([]User, error)
}
