// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountActiveAdmins(context.Context) (int64, error)
	CreateCaseType(context.Context, CreateCaseTypeParams) (CaseType, error)
	CreateUnit(context.Context, CreateUnitParams) (Unit, error)
	CreateUser(context.Context, CreateUserParams) (User, error)
	GetCaseType(context.Context, pgtype.UUID) (CaseType, error)
	GetUnit(context.Context, pgtype.UUID) (Unit, error)
	GetUser(context.Context, pgtype.UUID) (User, error)
	GetUserByFirebaseUID(context.Context, string) (User, error)
	ListCaseTypes(context.Context) ([]CaseType, error)
	ListUnits(context.Context) ([]Unit, error)
	ListUsers(context.Context, ListUsersParams) ([]ListUsersRow, error)
	ListUsersByUnit(context.Context, pgtype.UUID) ([]User, error)
	UpdateUser(context.Context, UpdateUserParams) (User, error)
}
