// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AppendCaseAuditEvent(context.Context, AppendCaseAuditEventParams) (AuditEvent, error)
	AppendPolicyAuditEvent(context.Context, AppendPolicyAuditEventParams) (AuditEvent, error)
	CountActiveAdmins(context.Context) (int64, error)
	CountActiveParticipantsByRole(context.Context, CountActiveParticipantsByRoleParams) (int64, error)
	CreateCase(context.Context, CreateCaseParams) (Case, error)
	CreateCaseParticipant(context.Context, CreateCaseParticipantParams) (CaseParticipant, error)
	CreateCaseType(context.Context, CreateCaseTypeParams) (CaseType, error)
	CreateUnit(context.Context, CreateUnitParams) (Unit, error)
	CreateUser(context.Context, CreateUserParams) (User, error)
	GetActiveParticipantForUpdate(context.Context, pgtype.UUID) (CaseParticipant, error)
	GetCase(context.Context, pgtype.UUID) (Case, error)
	GetCaseForUpdate(context.Context, pgtype.UUID) (Case, error)
	GetCaseType(context.Context, pgtype.UUID) (CaseType, error)
	GetParticipantByCaseUserRole(context.Context, GetParticipantByCaseUserRoleParams) (CaseParticipant, error)
	GetUnit(context.Context, pgtype.UUID) (Unit, error)
	GetUser(context.Context, pgtype.UUID) (User, error)
	GetUserByFirebaseUID(context.Context, string) (User, error)
	GetUserForUpdate(context.Context, pgtype.UUID) (User, error)
	IsActiveCaseParticipant(context.Context, IsActiveCaseParticipantParams) (bool, error)
	ListCaseAuditEvents(context.Context, pgtype.UUID) ([]AuditEvent, error)
	ListCaseParticipants(context.Context, pgtype.UUID) ([]CaseParticipant, error)
	ListCaseTypes(context.Context) ([]CaseType, error)
	ListCasesByOwner(context.Context, pgtype.UUID) ([]Case, error)
	ListCasesForUser(context.Context, ListCasesForUserParams) ([]Case, error)
	ListUnits(context.Context) ([]Unit, error)
	ListUsers(context.Context, ListUsersParams) ([]ListUsersRow, error)
	ListUsersByUnit(context.Context, pgtype.UUID) ([]User, error)
	ReactivateCaseParticipant(context.Context, ReactivateCaseParticipantParams) (CaseParticipant, error)
	UnassignCaseParticipant(context.Context, pgtype.UUID) (CaseParticipant, error)
	UpdateCase(context.Context, UpdateCaseParams) (Case, error)
	UpdateCaseStatus(context.Context, UpdateCaseStatusParams) (Case, error)
	UpdateUser(context.Context, UpdateUserParams) (User, error)
}
