// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const seedUnit = `-- name: SeedUnit :execrows
INSERT INTO units (id, code, name, description, created_at, updated_at)
VALUES (
    $1, $2, $3, $4,
    TIMESTAMPTZ '2025-01-15 09:00:00+00', TIMESTAMPTZ '2025-01-15 09:00:00+00'
)
ON CONFLICT DO NOTHING`

type SeedUnitParams struct {
	ID          pgtype.UUID
	Code        string
	Name        string
	Description pgtype.Text
}

func (q *Queries) SeedUnit(ctx context.Context, arg SeedUnitParams) (int64, error) {
	result, err := q.dbx.Exec(ctx, seedUnit, arg.ID, arg.Code, arg.Name, arg.Description)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const seedUser = `-- name: SeedUser :execrows
INSERT INTO users (
    id, unit_id, firebase_uid, name, email, status, system_role, created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, 'ACTIVE', $6,
    TIMESTAMPTZ '2025-01-15 09:00:00+00', TIMESTAMPTZ '2025-01-15 09:00:00+00'
)
ON CONFLICT DO NOTHING`

type SeedUserParams struct {
	ID          pgtype.UUID
	UnitID      pgtype.UUID
	FirebaseUID string
	Name        string
	Email       string
	SystemRole  string
}

func (q *Queries) SeedUser(ctx context.Context, arg SeedUserParams) (int64, error) {
	result, err := q.dbx.Exec(ctx, seedUser, arg.ID, arg.UnitID, arg.FirebaseUID, arg.Name, arg.Email, arg.SystemRole)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const seedCaseType = `-- name: SeedCaseType :execrows
INSERT INTO case_types (id, code, name, description, created_at, updated_at)
VALUES (
    $1, $2, $3, $4,
    TIMESTAMPTZ '2025-01-15 09:00:00+00', TIMESTAMPTZ '2025-01-15 09:00:00+00'
)
ON CONFLICT DO NOTHING`

type SeedCaseTypeParams struct {
	ID          pgtype.UUID
	Code        string
	Name        string
	Description pgtype.Text
}

func (q *Queries) SeedCaseType(ctx context.Context, arg SeedCaseTypeParams) (int64, error) {
	result, err := q.dbx.Exec(ctx, seedCaseType, arg.ID, arg.Code, arg.Name, arg.Description)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const seedPolicy = `-- name: SeedPolicy :execrows
INSERT INTO policies (
    id, code, title, domain, case_type_id, description, created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    TIMESTAMPTZ '2025-01-15 09:00:00+00', TIMESTAMPTZ '2025-01-15 09:00:00+00'
)
ON CONFLICT DO NOTHING`

type SeedPolicyParams struct {
	ID          pgtype.UUID
	Code        string
	Title       string
	Domain      string
	CaseTypeID  pgtype.UUID
	Description pgtype.Text
}

func (q *Queries) SeedPolicy(ctx context.Context, arg SeedPolicyParams) (int64, error) {
	result, err := q.dbx.Exec(ctx, seedPolicy, arg.ID, arg.Code, arg.Title, arg.Domain, arg.CaseTypeID, arg.Description)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const seedPolicyVersion = `-- name: SeedPolicyVersion :execrows
INSERT INTO policy_versions (
    id, policy_id, version, status, index_status, indexed_at, content,
    effective_from, created_by, approved_by, created_at, approved_at
)
VALUES (
    $1, $2, '1.0', 'ACTIVE', 'READY',
    TIMESTAMPTZ '2025-01-15 09:00:00+00', $3,
    TIMESTAMPTZ '2025-01-01 00:00:00+00', $4, $5,
    TIMESTAMPTZ '2025-01-15 09:00:00+00', TIMESTAMPTZ '2025-01-15 09:00:00+00'
)
ON CONFLICT DO NOTHING`

type SeedPolicyVersionParams struct {
	ID         pgtype.UUID
	PolicyID   pgtype.UUID
	Content    string
	CreatedBy  pgtype.UUID
	ApprovedBy pgtype.UUID
}

func (q *Queries) SeedPolicyVersion(ctx context.Context, arg SeedPolicyVersionParams) (int64, error) {
	result, err := q.dbx.Exec(ctx, seedPolicyVersion, arg.ID, arg.PolicyID, arg.Content, arg.CreatedBy, arg.ApprovedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const seedCase = `-- name: SeedCase :execrows
INSERT INTO cases (
    id, case_number, case_type_id, title, description, urgency, status,
    created_by, owner_id, created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $8,
    TIMESTAMPTZ '2025-01-15 09:00:00+00', TIMESTAMPTZ '2025-01-15 09:00:00+00'
)
ON CONFLICT DO NOTHING`

type SeedCaseParams struct {
	ID          pgtype.UUID
	CaseNumber  string
	CaseTypeID  pgtype.UUID
	Title       string
	Description string
	Urgency     string
	Status      string
	CreatedBy   pgtype.UUID
}

func (q *Queries) SeedCase(ctx context.Context, arg SeedCaseParams) (int64, error) {
	result, err := q.dbx.Exec(ctx, seedCase, arg.ID, arg.CaseNumber, arg.CaseTypeID, arg.Title, arg.Description, arg.Urgency, arg.Status, arg.CreatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const seedCaseParticipant = `-- name: SeedCaseParticipant :execrows
INSERT INTO case_participants (
    id, case_id, user_id, role, required, status, assigned_by, assigned_at
)
VALUES (
    $1, $2, $3, $4, $5, 'ACTIVE', $6,
    TIMESTAMPTZ '2025-01-15 09:00:00+00'
)
ON CONFLICT DO NOTHING`

type SeedCaseParticipantParams struct {
	ID         pgtype.UUID
	CaseID     pgtype.UUID
	UserID     pgtype.UUID
	Role       string
	Required   bool
	AssignedBy pgtype.UUID
}

func (q *Queries) SeedCaseParticipant(ctx context.Context, arg SeedCaseParticipantParams) (int64, error) {
	result, err := q.dbx.Exec(ctx, seedCaseParticipant, arg.ID, arg.CaseID, arg.UserID, arg.Role, arg.Required, arg.AssignedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const seedEvidence = `-- name: SeedEvidence :execrows
INSERT INTO case_evidences (
    id, case_id, source_type, source_user_id, evidence_type, title, content, created_at
)
VALUES (
    $1, $2, $3, $4, 'COMMENT', $5, $6,
    TIMESTAMPTZ '2025-01-15 09:00:00+00'
)
ON CONFLICT DO NOTHING`

type SeedEvidenceParams struct {
	ID           pgtype.UUID
	CaseID       pgtype.UUID
	SourceType   string
	SourceUserID pgtype.UUID
	Title        pgtype.Text
	Content      pgtype.Text
}

func (q *Queries) SeedEvidence(ctx context.Context, arg SeedEvidenceParams) (int64, error) {
	result, err := q.dbx.Exec(ctx, seedEvidence, arg.ID, arg.CaseID, arg.SourceType, arg.SourceUserID, arg.Title, arg.Content)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const seedCompletedAnalysis = `-- name: SeedCompletedAnalysis :execrows
INSERT INTO ai_analyses (
    id, case_id, version, status, summary, facts, assumptions, unknowns,
    risk_analysis, compliance_analysis, recommendation, alternatives,
    missing_information, policy_status, evidence_quality, uncertainty,
    verification_status, verification_notes, model_name, prompt_version, created_at
)
VALUES (
    $1, $2, 1, 'COMPLETED', $3,
    '[{"fact":"This is a synthetic demonstration fact."}]'::jsonb,
    '["All scenario details are fictional."]'::jsonb,
    '["No external records were consulted."]'::jsonb,
    '{"level":"LOW","notes":"Synthetic demonstration assessment only."}'::jsonb,
    '{"result":"DEMO_ONLY","notes":"No real policy or customer data was evaluated."}'::jsonb,
    '{"action":"Review the fictional example with the assigned demo participants."}'::jsonb,
    '[{"action":"Request additional synthetic context."}]'::jsonb,
    '["Additional fictional supporting detail."]'::jsonb,
    'POLICY_FOUND', 'MEDIUM', 'LOW', 'PASS_WITH_WARNING',
    '["Static seed output; not generated by an AI model."]'::jsonb,
    'demo-static-seed', 'demo-v1', TIMESTAMPTZ '2025-01-15 09:00:00+00'
)
ON CONFLICT DO NOTHING`

type SeedCompletedAnalysisParams struct {
	ID      pgtype.UUID
	CaseID  pgtype.UUID
	Summary pgtype.Text
}

func (q *Queries) SeedCompletedAnalysis(ctx context.Context, arg SeedCompletedAnalysisParams) (int64, error) {
	result, err := q.dbx.Exec(ctx, seedCompletedAnalysis, arg.ID, arg.CaseID, arg.Summary)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const seedCaseCurrentAnalysis = `-- name: SeedCaseCurrentAnalysis :execrows
UPDATE cases
SET current_analysis_id = $1
WHERE id = $2
  AND current_analysis_id IS NULL
  AND EXISTS (
      SELECT 1
      FROM ai_analyses AS analysis
      WHERE analysis.id = $1
        AND analysis.case_id = cases.id
        AND analysis.status = 'COMPLETED'
  )`

type SeedCaseCurrentAnalysisParams struct {
	AnalysisID pgtype.UUID
	CaseID     pgtype.UUID
}

func (q *Queries) SeedCaseCurrentAnalysis(ctx context.Context, arg SeedCaseCurrentAnalysisParams) (int64, error) {
	result, err := q.dbx.Exec(ctx, seedCaseCurrentAnalysis, arg.AnalysisID, arg.CaseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
