// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUnit = `-- name: CreateUnit :one
INSERT INTO units (id, code, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, code, name, description, created_at, updated_at`

type CreateUnitParams struct {
	ID          pgtype.UUID
	Code        string
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (Unit, error) {
	row := q.dbx.QueryRow(ctx, createUnit, arg.ID, arg.Code, arg.Name, arg.Description)
	var i Unit
	err := row.Scan(&i.ID, &i.Code, &i.Name, &i.Description, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getUnit = `-- name: GetUnit :one
SELECT id, code, name, description, created_at, updated_at
FROM units
WHERE id = $1`

func (q *Queries) GetUnit(ctx context.Context, id pgtype.UUID) (Unit, error) {
	row := q.dbx.QueryRow(ctx, getUnit, id)
	var i Unit
	err := row.Scan(&i.ID, &i.Code, &i.Name, &i.Description, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const listUnits = `-- name: ListUnits :many
SELECT id, code, name, description, created_at, updated_at
FROM units
ORDER BY name, id`

func (q *Queries) ListUnits(ctx context.Context) ([]Unit, error) {
	rows, err := q.dbx.Query(ctx, listUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]Unit, 0)
	for rows.Next() {
		var i Unit
		if err := rows.Scan(&i.ID, &i.Code, &i.Name, &i.Description, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
