// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, unit_id, firebase_uid, name, email)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, unit_id, firebase_uid, name, email, status, system_role, created_at, updated_at
`

type CreateUserParams struct {
	ID          pgtype.UUID
	UnitID      pgtype.UUID
	FirebaseUID string
	Name        string
	Email       string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.dbx.QueryRow(ctx, createUser,
		arg.ID,
		arg.UnitID,
		arg.FirebaseUID,
		arg.Name,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.FirebaseUID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.SystemRole,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, unit_id, firebase_uid, name, email, status, system_role, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.dbx.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.FirebaseUID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.SystemRole,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT id, unit_id, firebase_uid, name, email, status, system_role, created_at, updated_at
FROM users
WHERE firebase_uid = $1
`

func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUID string) (User, error) {
	row := q.dbx.QueryRow(ctx, getUserByFirebaseUID, firebaseUID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.FirebaseUID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.SystemRole,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersByUnit = `-- name: ListUsersByUnit :many
SELECT id, unit_id, firebase_uid, name, email, status, system_role, created_at, updated_at
FROM users
WHERE unit_id = $1
ORDER BY name, id
`

func (q *Queries) ListUsersByUnit(ctx context.Context, unitID pgtype.UUID) ([]User, error) {
	rows, err := q.dbx.Query(ctx, listUsersByUnit, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]User, 0)
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.FirebaseUID,
			&i.Name,
			&i.Email,
			&i.Status,
			&i.SystemRole,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
