-- Seed-only inserts use fixed identifiers supplied by internal/seed.  They are
-- intentionally insert-only: rerunning the tool never overwrites local data.

-- name: SeedUnit :execrows
INSERT INTO units (id, code, name, description, created_at, updated_at)
VALUES (
    sqlc.arg(id), sqlc.arg(code), sqlc.arg(name), sqlc.arg(description),
    TIMESTAMPTZ '2025-01-15 09:00:00+00', TIMESTAMPTZ '2025-01-15 09:00:00+00'
)
ON CONFLICT DO NOTHING;

-- name: SeedUser :execrows
INSERT INTO users (
    id, unit_id, firebase_uid, name, email, status, system_role, created_at, updated_at
)
VALUES (
    sqlc.arg(id), sqlc.arg(unit_id), sqlc.arg(firebase_uid), sqlc.arg(name),
    sqlc.arg(email), 'ACTIVE', sqlc.arg(system_role),
    TIMESTAMPTZ '2025-01-15 09:00:00+00', TIMESTAMPTZ '2025-01-15 09:00:00+00'
)
ON CONFLICT DO NOTHING;

-- name: SeedCaseType :execrows
INSERT INTO case_types (id, code, name, description, created_at, updated_at)
VALUES (
    sqlc.arg(id), sqlc.arg(code), sqlc.arg(name), sqlc.arg(description),
    TIMESTAMPTZ '2025-01-15 09:00:00+00', TIMESTAMPTZ '2025-01-15 09:00:00+00'
)
ON CONFLICT DO NOTHING;

-- name: SeedPolicy :execrows
INSERT INTO policies (
    id, code, title, domain, case_type_id, description, created_at, updated_at
)
VALUES (
    sqlc.arg(id), sqlc.arg(code), sqlc.arg(title), sqlc.arg(domain),
    sqlc.arg(case_type_id), sqlc.arg(description),
    TIMESTAMPTZ '2025-01-15 09:00:00+00', TIMESTAMPTZ '2025-01-15 09:00:00+00'
)
ON CONFLICT DO NOTHING;

-- name: SeedPolicyVersion :execrows
INSERT INTO policy_versions (
    id, policy_id, version, status, index_status, indexed_at, content,
    effective_from, created_by, approved_by, created_at, approved_at
)
VALUES (
    sqlc.arg(id), sqlc.arg(policy_id), '1.0', 'ACTIVE', 'READY',
    TIMESTAMPTZ '2025-01-15 09:00:00+00', sqlc.arg(content),
    TIMESTAMPTZ '2025-01-01 00:00:00+00', sqlc.arg(created_by), sqlc.arg(approved_by),
    TIMESTAMPTZ '2025-01-15 09:00:00+00', TIMESTAMPTZ '2025-01-15 09:00:00+00'
)
ON CONFLICT DO NOTHING;

-- name: SeedCase :execrows
INSERT INTO cases (
    id, case_number, case_type_id, title, description, urgency, status,
    created_by, owner_id, created_at, updated_at
)
VALUES (
    sqlc.arg(id), sqlc.arg(case_number), sqlc.arg(case_type_id), sqlc.arg(title),
    sqlc.arg(description), sqlc.arg(urgency), sqlc.arg(status),
    sqlc.arg(created_by), sqlc.arg(created_by),
    TIMESTAMPTZ '2025-01-15 09:00:00+00', TIMESTAMPTZ '2025-01-15 09:00:00+00'
)
ON CONFLICT DO NOTHING;

-- name: SeedCaseParticipant :execrows
INSERT INTO case_participants (
    id, case_id, user_id, role, required, status, assigned_by, assigned_at
)
VALUES (
    sqlc.arg(id), sqlc.arg(case_id), sqlc.arg(user_id), sqlc.arg(role),
    sqlc.arg(required), 'ACTIVE', sqlc.arg(assigned_by),
    TIMESTAMPTZ '2025-01-15 09:00:00+00'
)
ON CONFLICT DO NOTHING;

-- name: SeedEvidence :execrows
INSERT INTO case_evidences (
    id, case_id, source_type, source_user_id, evidence_type, title, content, created_at
)
VALUES (
    sqlc.arg(id), sqlc.arg(case_id), sqlc.arg(source_type), sqlc.arg(source_user_id),
    'COMMENT', sqlc.arg(title), sqlc.arg(content), TIMESTAMPTZ '2025-01-15 09:00:00+00'
)
ON CONFLICT DO NOTHING;

-- name: SeedCompletedAnalysis :execrows
INSERT INTO ai_analyses (
    id, case_id, version, status, summary, facts, assumptions, unknowns,
    risk_analysis, compliance_analysis, recommendation, alternatives,
    missing_information, policy_status, evidence_quality, uncertainty,
    verification_status, verification_notes, model_name, prompt_version, created_at
)
VALUES (
    sqlc.arg(id), sqlc.arg(case_id), 1, 'COMPLETED', sqlc.arg(summary),
    '[{"fact":"This is a synthetic demonstration fact."}]'::jsonb,
    '["All scenario details are fictional."]'::jsonb,
    '["No external records were consulted."]'::jsonb,
    '{"level":"LOW","notes":"Synthetic demonstration assessment only."}'::jsonb,
    '{"result":"DEMO_ONLY","notes":"No real policy or customer data was evaluated."}'::jsonb,
    '{"action":"Review the fictional example with the assigned demo participants."}'::jsonb,
    '[{"action":"Request additional synthetic context."}]'::jsonb,
    '["Additional fictional supporting detail."]'::jsonb,
    'POLICY_FOUND', 'MEDIUM', 'LOW', 'PASS_WITH_WARNING',
    '["Static seed output; not generated by an AI model."]'::jsonb,
    'demo-static-seed', 'demo-v1', TIMESTAMPTZ '2025-01-15 09:00:00+00'
)
ON CONFLICT DO NOTHING;

-- name: SeedCaseCurrentAnalysis :execrows
UPDATE cases
SET current_analysis_id = sqlc.arg(analysis_id)
WHERE id = sqlc.arg(case_id)
  AND current_analysis_id IS NULL
  AND EXISTS (
      SELECT 1
      FROM ai_analyses AS analysis
      WHERE analysis.id = sqlc.arg(analysis_id)
        AND analysis.case_id = cases.id
        AND analysis.status = 'COMPLETED'
  );
